### ISSUE TITLE
Quota Limits reached in Walidator

### ISSUE THREAD

**Issue by tbergmueller** [ethereum/ERCs#45]
### Pull Request

43

### What happened?

EIP Walidator fails to run, as it hits quota limits;
Refer https://github.com/ethereum/ERCs/actions/runs/6664676695/job/18112762062?pr=43

```
2023-10-27T08:17:18.7430627Z ##[group]Run ethereum/eipw-action@6858f56d1d9e5cbe49a0afd85150669f6983ed20
2023-10-27T08:17:18.7431484Z with:
2023-10-27T08:17:18.7432800Z   token: ***
2023-10-27T08:17:18.7433175Z   unchecked: 1
2023-10-27T08:17:18.7433562Z   path: ERCS/
2023-10-27T08:17:18.7433976Z   options-file: config/eipw.toml
2023-10-27T08:17:18.7434476Z ##[endgroup]
2023-10-27T08:17:19.4213347Z Request quota exhausted for request GET https://api.github.com/repos/ethereum/ERCs/pulls/43/files
2023-10-27T08:17:19.4214730Z Retrying after 1751 seconds!
2023-10-27T08:46:30.6570178Z Request quota exhausted for request GET https://api.github.com/repos/ethereum/ERCs/pulls/43/files
2023-10-27T08:46:30.6571285Z Retrying after 0 seconds!
```

### Relevant log output

```shell
2023-10-27T08:17:18.2926106Z Resolving deltas:  95% (92/96)
2023-10-27T08:17:18.2926598Z Resolving deltas:  96% (93/96)
2023-10-27T08:17:18.2927103Z Resolving deltas:  97% (94/96)
2023-10-27T08:17:18.2968699Z Resolving deltas:  98% (95/96)
2023-10-27T08:17:18.2969660Z Resolving deltas: 100% (96/96)
2023-10-27T08:17:18.2970193Z Resolving deltas: 100% (96/96), done.
2023-10-27T08:17:18.3648393Z From https://github.com/ethereum/ERCs
2023-10-27T08:17:18.3649969Z  * [new ref]         ed28201473f772b953998fe7e49f3a284a655866 -> pull/43/merge
2023-10-27T08:17:18.3680115Z ##[endgroup]
2023-10-27T08:17:18.3681065Z ##[group]Determining the checkout info
2023-10-27T08:17:18.3683078Z ##[endgroup]
2023-10-27T08:17:18.3683994Z ##[group]Checking out the ref
2023-10-27T08:17:18.3690140Z [command]/usr/bin/git checkout --progress --force refs/remotes/pull/43/merge
2023-10-27T08:17:18.6841119Z Note: switching to 'refs/remotes/pull/43/merge'.
2023-10-27T08:17:18.6841912Z 
2023-10-27T08:17:18.6842930Z You are in 'detached HEAD' state. You can look around, make experimental
2023-10-27T08:17:18.6844180Z changes and commit them, and you can discard any commits you make in this
2023-10-27T08:17:18.6845373Z state without impacting any branches by switching back to a branch.
2023-10-27T08:17:18.6846151Z 
2023-10-27T08:17:18.6852155Z If you want to create a new branch to retain commits you create, you may
2023-10-27T08:17:18.6853525Z do so (now or later) by using -c with the switch command. Example:
2023-10-27T08:17:18.6854492Z 
2023-10-27T08:17:18.6854846Z   git switch -c <new-branch-name>
2023-10-27T08:17:18.6855315Z 
2023-10-27T08:17:18.6855575Z Or undo this operation with:
2023-10-27T08:17:18.6856016Z 
2023-10-27T08:17:18.6856242Z   git switch -
2023-10-27T08:17:18.6856573Z 
2023-10-27T08:17:18.6857136Z Turn off this advice by setting config variable advice.detachedHead to false
2023-10-27T08:17:18.6857941Z 
2023-10-27T08:17:18.6858811Z HEAD is now at ed28201 Merge ba664d607145f45456d605275c3841afe2b49d5f into a5f4f4632e6df7915343fdbfa57ce4d270cf2562
2023-10-27T08:17:18.6877596Z ##[endgroup]
2023-10-27T08:17:18.6936305Z [command]/usr/bin/git log -1 --format='%H'
2023-10-27T08:17:18.6976128Z 'ed28201473f772b953998fe7e49f3a284a655866'
2023-10-27T08:17:18.7430627Z ##[group]Run ethereum/eipw-action@6858f56d1d9e5cbe49a0afd85150669f6983ed20
2023-10-27T08:17:18.7431484Z with:
2023-10-27T08:17:18.7432800Z   token: ***
2023-10-27T08:17:18.7433175Z   unchecked: 1
2023-10-27T08:17:18.7433562Z   path: ERCS/
2023-10-27T08:17:18.7433976Z   options-file: config/eipw.toml
2023-10-27T08:17:18.7434476Z ##[endgroup]
2023-10-27T08:17:19.4213347Z Request quota exhausted for request GET https://api.github.com/repos/ethereum/ERCs/pulls/43/files
2023-10-27T08:17:19.4214730Z Retrying after 1751 seconds!
2023-10-27T08:46:30.6570178Z Request quota exhausted for request GET https://api.github.com/repos/ethereum/ERCs/pulls/43/files
2023-10-27T08:46:30.6571285Z Retrying after 0 seconds!
2023-10-27T08:46:30.8135944Z Request quota exhausted for request GET https://api.github.com/repos/ethereum/ERCs/pulls/43/files
2023-10-27T08:46:30.8137215Z Retrying after 0 seconds!
2023-10-27T08:46:30.9641981Z Request quota exhausted for request GET https://api.github.com/repos/ethereum/ERCs/pulls/43/files
2023-10-27T08:46:30.9700847Z RequestError [HttpError]: API rate limit exceeded for installation ID 2246695. If you reach out to GitHub Support for help, please include the request ID 7C80:4BF1:169136D:176DA4E:653B78E6.
2023-10-27T08:46:30.9703860Z     at /home/runner/work/_actions/ethereum/eipw-action/6858f56d1d9e5cbe49a0afd85150669f6983ed20/dist/index.js:6691:25
2023-10-27T08:46:30.9705643Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-27T08:46:30.9707818Z     at async Job.doExecute (/home/runner/work/_actions/ethereum/eipw-action/6858f56d1d9e5cbe49a0afd85150669f6983ed20/dist/index.js:8747:22) {
2023-10-27T08:46:30.9709374Z   status: 403,
2023-10-27T08:46:30.9710259Z   response: {
2023-10-27T08:46:30.9711902Z     url: 'https://api.github.com/repos/ethereum/ERCs/pulls/43/files',
2023-10-27T08:46:30.9712700Z     status: 403,
2023-10-27T08:46:30.9713144Z     headers: {
2023-10-27T08:46:30.9713650Z       'access-control-allow-origin': '*',
2023-10-27T08:46:30.9722362Z       'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
2023-10-27T08:46:30.9725524Z       'content-encoding': 'gzip',
2023-10-27T08:46:30.9726256Z       'content-security-policy': "default-src 'none'",
2023-10-27T08:46:30.9727125Z       'content-type': 'application/json; charset=utf-8',
2023-10-27T08:46:30.9727919Z       date: 'Fri, 27 Oct 2023 08:46:30 GMT',
2023-10-27T08:46:30.9728994Z       'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
2023-10-27T08:46:30.9729973Z       server: 'GitHub.com',
2023-10-27T08:46:30.9730895Z       'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
2023-10-27T08:46:30.9731876Z       'transfer-encoding': 'chunked',
2023-10-27T08:46:30.9732643Z       vary: 'Accept-Encoding, Accept, X-Requested-With',
2023-10-27T08:46:30.9733442Z       'x-content-type-options': 'nosniff',
2023-10-27T08:46:30.9736040Z       'x-frame-options': 'deny',
2023-10-27T08:46:30.9736770Z       'x-github-media-type': 'github.v3; format=json',
2023-10-27T08:46:30.9737712Z       'x-github-request-id': '7C80:4BF1:169136D:176DA4E:653B78E6',
2023-10-27T08:46:30.9738517Z       'x-ratelimit-limit': '1000',
2023-10-27T08:46:30.9739129Z       'x-ratelimit-remaining': '0',
2023-10-27T08:46:30.9739757Z       'x-ratelimit-reset': '1698396390',
2023-10-27T08:46:30.9740415Z       'x-ratelimit-resource': 'core',
2023-10-27T08:46:30.9741039Z       'x-ratelimit-used': '1003',
2023-10-27T08:46:30.9741607Z       'x-xss-protection': '0'
2023-10-27T08:46:30.9742074Z     },
2023-10-27T08:46:30.9742403Z     data: {
2023-10-27T08:46:30.9744379Z       message: 'API rate limit exceeded for installation ID 2246695. If you reach out to GitHub Support for help, please include the request ID 7C80:4BF1:169136D:176DA4E:653B78E6.',
2023-10-27T08:46:30.9746692Z       documentation_url: 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'
2023-10-27T08:46:30.9747744Z     }
2023-10-27T08:46:30.9748045Z   },
2023-10-27T08:46:30.9748370Z   request: {
2023-10-27T08:46:30.9748783Z     method: 'GET',
2023-10-27T08:46:30.9749506Z     url: 'https://api.github.com/repos/ethereum/ERCs/pulls/43/files',
2023-10-27T08:46:30.9750280Z     headers: {
2023-10-27T08:46:30.9750818Z       accept: 'application/vnd.github.v3+json',
2023-10-27T08:46:30.9751759Z       'user-agent': 'octokit-core.js/3.6.0 Node.js/20.8.1 (linux; x64)',
2023-10-27T08:46:30.9752636Z       authorization: 'token [REDACTED]'
2023-10-27T08:46:30.9753182Z     },
2023-10-27T08:46:30.9753503Z     request: {
2023-10-27T08:46:30.9753928Z       agent: [Agent],
2023-10-27T08:46:30.9754424Z       hook: [Function: bound bound register],
2023-10-27T08:46:30.9755006Z       retryCount: 2
2023-10-27T08:46:30.9755390Z     }
2023-10-27T08:46:30.9755716Z   }
2023-10-27T08:46:30.9756008Z }
2023-10-27T08:46:30.9795088Z ##[error]API rate limit exceeded for installation ID 2246695. If you reach out to GitHub Support for help, please include the request ID 7C80:4BF1:169136D:176DA4E:653B78E6.
2023-10-27T08:46:30.9948397Z Post job cleanup.
2023-10-27T08:46:31.1356185Z [command]/usr/bin/git version
2023-10-27T08:46:31.1415055Z git version 2.42.0
2023-10-27T08:46:31.1469921Z Temporarily overriding HOME='/home/runner/work/_temp/356dc8ac-02e1-4d8d-a597-143f04bf7d0d' before making global git config changes
2023-10-27T08:46:31.1471950Z Adding repository directory to the temporary git global config as a safe directory
2023-10-27T08:46:31.1478690Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/ERCs/ERCs
2023-10-27T08:46:31.1532604Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2023-10-27T08:46:31.1580892Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2023-10-27T08:46:31.1912725Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2023-10-27T08:46:31.1957589Z http.https://github.com/.extraheader
2023-10-27T08:46:31.1973757Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2023-10-27T08:46:31.2021639Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2023-10-27T08:46:31.2739924Z Cleaning up orphan processes
```

**Comment by Pandapip1** [comment]
This is a limitation of the GitHub API. I dp believe that there could be a better error message though. Please open an issue on the Walidator repository.

**Comment by Pandapip1** [comment]
Or CC @SamWilsn to transfer the issue
